from tortoise import fields, models


class HealthRecord(models.Model):
    id = fields.BigIntField(primary_key=True)
    user = fields.ForeignKeyField("models.User", related_name="health_records")
    height_cm = fields.DecimalField(max_digits=5, decimal_places=2, null=True)
    weight_kg = fields.DecimalField(max_digits=5, decimal_places=2, null=True)
    waist_cm = fields.DecimalField(max_digits=5, decimal_places=2, null=True)
    bmi = fields.DecimalField(max_digits=5, decimal_places=2, null=True)
    systolic_bp = fields.IntField(null=True)
    diastolic_bp = fields.IntField(null=True)
    fasting_glucose = fields.IntField(null=True)
    hba1c = fields.DecimalField(max_digits=4, decimal_places=2, null=True)
    total_cholesterol = fields.IntField(null=True)
    ldl_cholesterol = fields.IntField(null=True)
    hdl_cholesterol = fields.IntField(null=True)
    triglyceride = fields.IntField(null=True)
    ast = fields.IntField(null=True)
    alt = fields.IntField(null=True)
    gamma_gtp = fields.IntField(null=True)
    creatinine = fields.DecimalField(max_digits=5, decimal_places=2, null=True)
    egfr = fields.DecimalField(max_digits=6, decimal_places=2, null=True)
    hemoglobin = fields.DecimalField(max_digits=5, decimal_places=2, null=True)
    has_diabetes = fields.BooleanField(null=True)
    has_obesity = fields.BooleanField(null=True)
    has_dyslipidemia = fields.BooleanField(null=True)
    has_hypertension = fields.BooleanField(null=True)
    occupation_code = fields.CharField(max_length=30, null=True)
    family_htn = fields.CharField(max_length=10, null=True)
    family_dm = fields.CharField(max_length=10, null=True)
    family_dyslipidemia = fields.CharField(max_length=10, null=True)
    smoking_status = fields.CharField(max_length=20, null=True)
    drinking_frequency = fields.CharField(max_length=30, null=True)
    drinking_amount = fields.CharField(max_length=30, null=True)
    walking_days_per_week = fields.IntField(null=True)
    strength_days_per_week = fields.IntField(null=True)
    sleep_hours = fields.DecimalField(max_digits=4, decimal_places=2, null=True)
    source = fields.CharField(max_length=30, default="MANUAL")
    measured_at = fields.DatetimeField()
    created_at = fields.DatetimeField(auto_now_add=True)
    updated_at = fields.DatetimeField(auto_now=True)

    class Meta:
        table = "health_records"
        indexes = (("user_id", "measured_at"),)
